baseURL = "https://tsukino.top"
languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
title = "Thoughts@Tsukino"
copyright = '© Dustin Jiang'

timeZone = "Asia/Shanghai"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      extra = true

      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = true
        [markup.goldmark.extensions.extras.insert]
          enable = true
        [markup.goldmark.extensions.extras.mark]
          enable = true
        [markup.goldmark.extensions.extras.subscript]
          enable = true
        [markup.goldmark.extensions.extras.superscript]
          enable = true
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]

  [markup.highlight]
    lineNos = true
    lineNumbersInTable = true
    noClasses = false

[params]
  description = "眼见何事, 情系何处, 身在何方, 心思何人?"
  [params.author]
    email = 'i@tsukino.top'
    name = "浅見ツキノ"

[taxonomies]
  tag = "tags"
  series = "series"
  # Used by notes
  category = "category"

[languages]
  [languages.en]
    weight = 2
  [languages.zh-cn]
    weight = 1
[services]
  [services.googleAnalytics]
    id = 'G-P8LEYB1KTM'