baseURL = "https://szclsya.me"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Leo's Field"
theme = "less"

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = true
    noClasses = false

[params]
  description = "Time to change drinks and mix... wait"
  author = "Leo Shen"
  staticFileBaseUrl = "https://static.szclsya.me"

[taxonomies]
  tag = "tags"
  series = "series"

[languages]
  [languages.en]
    weight = 1
  [languages.zh-cn]
    weight = 2
